# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2Y0NmU5NWU2MzAwYmE1Nzk5NTNmN2VhYzNkMzE1ZDBkZTFlZDc3NTFlZWM1OGNmYTE0MGUyZGQ1NWE0NzMxNzJmZTQ5MWU2YWMxYzIxYTU3YzNlOGVkNmI3OTQ1ZThlMDZkMGRhOTcwYmJlN2Y5M2Y3NjA2ZmNhNjFkYzRhOWU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
